with RECURSIVE GEN_ADD AS (
    SELECT ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID is null
    
    UNION ALL

    SELECT A.ID AS ID, GEN + 1 AS GEN
    FROM ECOLI_DATA AS A, GEN_ADD AS B
    WHERE A.PARENT_ID = B.ID
)

SELECT COUNT(GEN) AS COUNT, GEN AS GENERATION
FROM GEN_ADD
WHERE 1=1
AND ID NOT IN (SELECT DISTINCT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GEN;